<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>PuTTYLauncher.ico</ApplicationIcon>
    <Copyright>Copyright (c) Steve Ives, 2025</Copyright>
    <Description>A Windows desktop utility to help launch PuTTY SSH sessions with pre-defined usernames and passwords, automating the login process.</Description>
    <Authors>Steve Ives</Authors>
    <AssemblyVersion>1.4</AssemblyVersion>
    <FileVersion>1.4</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="PuTTYLauncher.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AppSettings.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
